# Generated by Django 4.1.6 on 2023-02-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField(verbose_name='Телеграм id')),
                ('user_name', models.CharField(max_length=150, verbose_name='Имя пользователя')),
                ('user_phone_number', models.CharField(max_length=13, verbose_name='Номер телефона')),
                ('user_service', models.CharField(max_length=75, verbose_name='Услуга')),
            ],
        ),
    ]
