# Generated by Django 4.1.6 on 2023-02-03 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=75)),
                ('service_added_name', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TgOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.tguser')),
                ('user_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.services')),
            ],
        ),
    ]
